#!/usr/bin/env python
import sys, os

from util.log import setup_logging

USAGE = "Usage: ./run <web|sched|once|queue|js>"

def main():
    if not len(sys.argv) > 1:
        print USAGE
        sys.exit(1)

    if sys.argv[1] == "web":
        setup_logging("web")
        from fort import app, setup, get_js_templates, get_js_source

        port = 5000
        if len(sys.argv) > 2 and sys.argv[2] == "test":
            print "Enabling test mode..."
            app.config["TESTING"] = True
            port = 8321

        # Files we listen for changes on
        extra = list(get_js_templates()) + list(get_js_source())

        setup()
        app.run("0.0.0.0", port=port, debug=True, extra_files=extra)
        sys.exit(0)

    if sys.argv[1] == "queue":
        setup_logging("queue")
        from util.queue import start_queues
        start_queues()

    if sys.argv[1] == "sched":
        setup_logging("sched")
        from scheduler.run import sched
        sched.run()
        sys.exit(0)

    if sys.argv[1] == "js":
        from fort import build_js_templates
        build_js_templates()
        sys.exit(0)

    if sys.argv[1] == "once":
        setup_logging("sched-once")
        import scheduler.run

        if len(sys.argv) < 3:
            print "Usage: ./run.py once <task>"
            sys.exit(1)

        if sys.argv[2] in dir(scheduler.run):
            getattr(locals()["scheduler"].run, sys.argv[2])()
        sys.exit(0)

    print USAGE
    sys.exit(1)

if __name__ == "__main__":
    main()

