#!/usr/bin/env python
import sys, os

def main():
    if not len(sys.argv) > 1:
        print "Usage: ./run <web|tests>"
        sys.exit(1)

    if sys.argv[1] == "web":
        from emporium import app, setup
        setup()
        app.run(debug=True)

    if sys.argv[1] == "tests":
        os.system("python -m unittest discover tests '*.py'")

if __name__ == "__main__":
    main()
