#!/usr/bin/env python
import sys

def main():
    if not len(sys.argv) > 1:
        print "Usage: ./run <web>"
        sys.exit(1)

    if sys.argv[1] == "web":
        from emporium import app, setup
        setup()
        app.run(debug=True)

if __name__ == "__main__":
    main()
